config/routes.rb
Rails.application.routes.draw do
  root 'artists#index'

  resources :artists do
    resources :songs#, only: [:new, :create]
    # resources :photos
  end
  resources :photos
  # resources :songs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs, dependent: :destroy
  has_many :photos, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  # validates :image, length: { maximum: 255 }, allow_blank: true


  

end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :arist, optional: true

  mount_uploader :image, ImageUploader
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist, optional: true

  validates :title, presence: true
  # validates_numericality_of :year, only_integer: true, length: { maximum: 4 }, allow_blank:true

  # optional ordering
  def self.order_by_title
    order(:title)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  def index
    @artists = Artist.order(name: :asc)
  end

  def show; end

  def new
    @artist = Artist.new
  end

  def edit; end

  def update
    if @artist.update_attributes(artist_params)
      redirect_to @artist
    else
      render 'edit'
    end
  end

  def create
    @artist = Artist.new(artist_params) #build????

    if @artist.save
      redirect_to @artist, notice: "Artist successfully created"
    else
      render new_artist_path
    end
  end

  def destroy
    @artist.destroy

    redirect_to artists_path #ROOT
  end

  private

  def set_artist
    @artist = Artist.find(params[:id])
  end

  def artist_params
    params.require(:artist).permit(:name, :image)
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  # from book stefan wintermeyer
  before_action :set_artist
  before_action :set_song, only: [:show, :edit, :update, :destroy]
  # Why can't these be here?
  # respond_to :html
  # respond_to :js

  def index
  end

  def new
    # artist = Artist.find(params[:artist_id])
    @song = Song.new
    # from book  wintermeyer:
    # @song = artist.songs.build
  end

  def edit
  end

  def update
    if @song.update_attributes(song_params)
      redirect_to @song.artist, notice: "Song successfully changed"
    else
      render 'edit'
    end
  end

  def create
  #   # from book
    # @song = @artist.songs.build(song_params)
    # @song.save
    @song = Song.create(song_params.merge(artist_id: params[:artist_id]))
    respond_to do |format|
      format.html { redirect_to artist_path(@artist) }
      # format.json { render :show, status: :created, location: @artist }
      format.json { render json: @artist }
    end

    # redirect_to @song.artist
  #   # notice can go, because you can see if it was successful, but still want to try out where it shows and how to implement it.
  #   , notice: "Song successfully added to " + @song.artist.name + "!"
  end

  def destroy
    @song.destroy
    # Is the respond_to block optional when using partials and remote: true??
    respond_to do |format|
      format.html { redirect_to artist_path(@artist) }
      format.json { render json: @artist }
    end
    # redirect_back(fallback_location: root_path)
  end

  private

  def set_artist
    @artist = Artist.find(params[:artist_id])
  end

  def set_song
    @song = Song.find(params[:id])
  end


  def song_params
    params.require(:song).permit(:title, :album, :year, :artist_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">


  <!-- Error messages -->
    <% @artist.errors.full_messages.each do |msg| %>
      <p class="alert alert-danger"><%= msg %></p>
    <% end %>

    <%= form_for @artist do |f| %>

      <div class="form-group">
        <%= f.text_field :name, placeholder: "Name", class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.text_field :image, placeholder: "image", size: 50, class: "form-control" %>
      </div>

      <div class="actions">
        <%= f.submit "Save", class: "btn btn-primary" %>
      </div>
      <br>
      <div class="actions">
        <%= link_to "Back", artists_path, class: "btn btn-primary" %>
      </div>

    <% end %>

app/views/artists/_new_song_d.html.erb
<!-- In songs view -->

<div class="row">
  <div class="col-md-6 text-left">


  <!-- Error messages -->

    <h2>Add new song for <%=  @artist.name %> </h2>
    <%= form_for [@artist,@artist.songs.new], remote: true do |f| %>
    <%#= form_for [@artist, @song] do |f| %>

      <div class="form-group">
        <%= f.text_field :title, placeholder: "Title", class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.text_field :album, placeholder: "Album", class: "form-control" %>
      </div>

      <div class="form-group">
        Year of release:
        <%= f.date_select :year, {:start_year => Time.now.year, :end_year => Time.now.year - 95, :discard_day => true, :discard_month => true} %>

      </div>

      <div class="actions">
        <%= f.submit "Save", remote: true, class: "btn btn-primary" %>
      </div>

    <% end %>

app/views/artists/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3>Change artist information</h3>
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/artists/index.html.erb
<div class="row">
  <div class="col-md-10">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h4>Artists</h4>
      </div>
      <div class="panel-body">
        <% @artists.each do |artist| %>
        <div class="row">
          <div class="col-md-10">
            <h4> <%= artist.name %> </h4>
            <!-- <div class="col-md-10 right"> -->
              <%= link_to "View", artist, class: "btn btn-default" %>
              <%= link_to "Update", edit_artist_path(artist), class: "btn btn-default" %>
              <%= link_to "Delete", artist_path(artist), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default" %>
            <!-- </div> -->
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-10">
    <%= link_to "Add a new artist", new_artist_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/artists/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3>Add a new artist</h3>
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/artists/new_song.js.erb
// in artists controller

// $('#new-song-form').after("<%= j render('songs/new_song') %>");
// $('#new-song-form').hide();

$('#new-song-form').html("<%= j (render 'songs/new_song') %>");
$('#new-song-form').slideDown(350);

app/views/artists/show.html.erb
<div class="row">
  <div class="col-md-10">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h4><%= @artist.name %></h4>
      </div>
      <div class="panel-body">
        <%= @artist.image %>   <!-- image in the photo in the artist, nested resoureces?? -->

        <div id="all-songs">
          <%= render 'songs/list_songs' %>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-10">
    <div class="new_artist_song_path">

      <%= link_to "New Song", "#", class: "btn btn-primary new-song-btn" %>
    </div>
  </div>
</div>

<div id="new-song-form" style="display:none;">
  <%= render 'songs/new_song' %>
</div>




<!-- <br><br><hr>
<h4>Photos</h4> -->
<%# @artist.photos.each do |photo| %>
  <%#= image_tag photo.image %>
<%# end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codaisseurify</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
    <!-- , 'data-turbolinks-track': 'reload' -->

  </head>

  <body>
    <%= render 'shared/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<!-- Static navbar -->
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "All artists", root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">

          <li><%= link_to "Add new artist", new_artist_path %></li>
          <li>
            <% if @artist  %>
              <%= link_to "New Song", new_artist_song_path(@artist) %>
            <% end  %>
          </li>

      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/songs/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3 text-center">


  <!-- Error messages -->
    <% @song.errors.full_messages.each do |msg| %>
    <p class="alert alert-danger"><%= msg %></p>
  <% end %>

    <h2>Add new song for <%=  @artist %> </h2>
  <!-- TRY out form new registrations form -->
  <% debugger %>
    <%= form_for [@artist,@artist.songs.new] do |f| %>

      <div class="form-group">
        <%= f.text_field :title, placeholder: "Title", class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.text_field :album, placeholder: "Album", class: "form-control" %>
      </div>

      <div class="form-group">
        Year of release:
        <%= f.date_select :year, {:start_year => Time.now.year, :end_year => Time.now.year - 95, :discard_day => true, :discard_month => true} %>

      </div>

      <div class="actions">
        <%= f.submit "Save", class: "btn btn-primary" %>
      </div>

    <% end %>

app/views/songs/_list_songs.html.erb
<% @artist.songs.each do |song| %>
<div class="row">
  <div class="col-md-9">
    <div class="song-line" data-id="<%= song.id %>">
      <h5> <%= song.title %> </h5>
      <%= link_to "Edit song", edit_artist_song_path(@artist, song), remote: true, class: "btn btn-default" %>
      <%= link_to "Delete", artist_song_path(@artist, song), remote: true, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default" %>
      <%= link_to "View", artist_song_path(@artist, song), class: "btn btn-default" %>
    </div>
  </div>
</div>
<% end %>
<hr>

<%= link_to "Delete all songs", "#", data: { confirm: "I couldn't get this working unfortunately :(" }, class: "btn btn-default delete-all-songs" %>

app/views/songs/_new_song.html.erb
<!-- In songs view -->

<div class="row">
  <div class="col-md-6 text-left">


  <!-- Error messages -->



    <h2>Add new song for <%=  @artist.name %> </h2>
    <%= form_for [@artist,@artist.songs.new] do |f| %>
    <%#= form_for [@artist, @song], remote: true do |f| %>

      <div class="form-group">
        <%= f.text_field :title, placeholder: "Title", class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.text_field :album, placeholder: "Album", class: "form-control" %>
      </div>

      <div class="form-group">
        Year of release:
        <%= f.date_select :year, {:start_year => Time.now.year, :end_year => Time.now.year - 95, :discard_day => true, :discard_month => true} %>

      </div>

      <div class="actions">
        <%= f.submit "Save", class: "btn btn-primary submit-new-song" %>
      </div>

    <% end %>

app/views/songs/create.js.erb
// $("#all-songs").html("<%= j render 'songs/list_songs'  %>");

app/views/songs/destroy.js.erb
// $("#all-songs").html("<%= j render 'songs/list_songs'  %>");

app/views/songs/edit.html.erb
<h1>Songs#edit</h1>
<p>Find me in app/views/songs/edit.html.erb</p>

app/views/songs/index.html.erb
<h1>Songs#index</h1>
<p>Find me in app/views/songs/index.html.erb</p>

app/views/songs/new.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-3">

    <!-- Error messages, Where is the notice inserted???? FIXME-->
      <% @song.errors.full_messages.each do |msg| %>
      <p class="alert alert-danger"><%= msg %></p>
    <% end %>

    <h2>Add new song for <%=  @artist.name %> </h2>
  <!-- TRY out form new registrations form -->
    <%= form_for [@artist, @song] do |f| %>

      <div class="form-group">
        <%= f.text_field :title, placeholder: "Title", class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.text_field :album, placeholder: "Album", class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :year %>
        <%= f.number_field :year, size: 4, within: 1500..2100, class: "form-control" %>
      </div>

      <div class="actions">
        <%= f.submit "Save", class: "btn btn-primary" %>
      </div>

    <% end %>

  </div>
</div>
<br>
<div class="row">
  <div class="col-md-10">
    <%= link_to "Back", artist_path(@artist), class: "btn btn-primary" %>
  </div>
</div>

app/views/songs/new_temp_duplicate.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-3">

    <!-- Error messages, Where is the notice inserted???? FIXME-->
      <% @song.errors.full_messages.each do |msg| %>
      <p class="alert alert-danger"><%= msg %></p>
    <% end %>

    <h2>Add new song for <%=  @artist.name %> </h2>
  <!-- TRY out form new registrations form -->
    <%= form_for [@artist, @song] do |f| %>

      <div class="form-group">
        <%= f.text_field :title, placeholder: "Title", class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.text_field :album, placeholder: "Album", class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :year %>
        <%= f.number_field :year, size: 4, within: 1500..2100, class: "form-control" %>
      </div>

      <div class="actions">
        <%= f.submit "Save", class: "btn btn-primary" %>
      </div>

    <% end %>

  </div>
</div>
<br>
<div class="row">
  <div class="col-md-10">
    <%= link_to "Back", artist_path(@artist), class: "btn btn-primary" %>
  </div>
</div>